name: CI | Build
on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: string
        default: no

jobs:
  build-everything:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host_os:
          - fedora
          - rhel
    env:
      HOST_OS: ${{ matrix.host_os }}
    steps:
      - name: Build step
        if: ${{ inputs.skip != 'yes' }}
        run: |
          true
      - name: Skip build
        if: ${{ inputs.skip == 'yes' }}
        run: |
          true

