name: PR CI
on:
  pull_request:
    types:
      - open
      - synchronize
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  skipper:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/gatekeeper-skipper.yaml
    with:
      commit-hash: ${{ github.event.pull_request.head.sha }}
      target-branch: ${{ github.event.pull_request.base.ref }}

  ci-on-push:
    needs: skipper
    if: ${{ needs.skipper.outputs.skip_build != 'yes' }}
    run: echo "Running Dummy task"