name: Run the CI
on:
  workflow_call:
    inputs:
      commit-hash:
        required: true
        type: string
      pr-number:
        required: true
        type: string
      tag:
        required: true
        type: string
      target-branch:
        required: false
        type: string
        default: ""

jobs:
  skipper:
    uses: ./.github/workflows/gatekeeper-skipper.yaml
    with:
      commit-hash: ${{ github.event.pull_request.head.sha }}
      target-branch: ${{ github.event.pull_request.base.ref }}

  job1:
    needs: skipper
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          echo "STATIC: $SKIP_STATIC"
          echo "TEST: $SKIP_TEST"
          echo "BUILD: $SKIP_BUILD"
          env
          echo "STATIC: $SKIP_STATIC"
          echo "TEST: $SKIP_TEST"
          echo "BUILD: $SKIP_BUILD"
        env:
          SKIP_STATIC: ${{ needs.skipper.outputs.skip_static }}
          SKIP_TEST: ${{ needs.skipper.outputs.skip_test }}
          SKIP_BUILD: ${{ needs.skipper.outputs.skip_build }}

  job2:
    needs: skipper
    uses: ./.github/workflows/job2.yaml
    with:
      skip-static: ${{ needs.skipper.outputs.skip_static }}
      skip-tests: ${{ needs.skipper.outputs.skip_test }}
      skip-build: ${{ needs.skipper.outputs.skip_build }}

#  build:
#    needs: skipper
#    if: ${{ needs.skipper.outputs.skip_build }}
#    uses: ./.github/workflows/build.yaml
#
#  test:
#    needs: [build, skipper]
#    if: ${{ needs.skipper.outputs.skip_test }}
#    uses: ./.github/workflows/test.yaml
