name: Job2
on:
  workflow_call:
    inputs:
      skip-tests:
        required: true
        type: string
      skip-build:
        required: true
        type: string
      skip-static:
        required: true
        type: string

jobs:
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          echo "STATIC: $SKIP_STATIC"
          echo "TEST: $SKIP_TEST"
          echo "BUILD: $SKIP_BUILD"
          env
          echo "STATIC: $SKIP_STATIC"
          echo "TEST: $SKIP_TEST"
          echo "BUILD: $SKIP_BUILD"
        env:
          SKIP_STATIC: ${{ inputs.skip-static }}
          SKIP_TEST: ${{ inputs.skip-test }}
          SKIP_BUILD: ${{ inputs.skip-build }}
