name: CI | Test
on:
  workflow_call:

jobs:
  runs-on: ubuntu-latest
  build-everything:
    strategy:
      matrix:
        vmm:
          - qemu
          - clh
    env:
      VMM: ${{ matrix.vmm }}
    steps:
      - name: Build step
        run: |
          true

