name: CI | Test
on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: string
        default: no

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vmm:
          - qemu
          - clh
    env:
      VMM: ${{ matrix.vmm }}
    steps:
      - name: Perform test
        if: ${{ inputs.skip != 'yes' }}
        run: |
          true
      - name: Skip test
        if: ${{ inputs.skip == 'yes' }}
        run: |
          true
