name: CI | Test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vmm:
          - qemu
          - clh
    env:
      VMM: ${{ matrix.vmm }}
    steps:
      - name: Perform test
        run: |
          true
